version: '3.8'

services:
  webapp:
    image: dracgr/samplewebapp
    ports:
      - "3100:80"
    volumes:
      - type: bind
        source: /home/gouthamgr/Desktop/
        target: /usr/local/apache2/htdocs/
    deploy:
      replicas: 5

